version: "3.9"
services:
  backend:
    build: ./backend 
    privileged: true
    ports: 
      - 8000:8000
      - 52362:52362
    # network_mode: host
    volumes:
      - ./backend/src:/opt/src

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    # network_mode: host
    volumes:
      - ./frontend/public:/opt/public
      - ./frontend/src:/opt/src
      - ./frontend/index.html:/opt/index.html
      - ./frontend/vite.config.js:/opt/vite.config.js
      - ./frontend/.eslintrc.cjs:/opt/.eslintrc.cjs